title: My first Blog Post
author: Eunnylans
email: eunice.igbinedion@yahoo.com
theme: minima
description: My First Week experience in WBS Bootcamp as a Full Stack Web-Dev
  Words cant decribe how excited i feel about the ongoing bootcamp, i must say all expectations are met. Good-stuff Wbs code academy.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
